FROM debian:jessie
MAINTAINER Greg Burton "gburton@gmail.com"

ENV VERSION 1.0

RUN apt-get update

# CUrl
RUN apt-get -y install curl

# Dependencies
RUN echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list

# Git, SBT
RUN apt-get update && \
    apt-get -y --fix-missing install wget bzip2 && \
    apt-get -y --force-yes --fix-missing install --no-install-recommends git sbt && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Scala
RUN curl -O -q http://downloads.typesafe.com/scala/2.11.5/scala-2.11.5.deb && \
    dpkg -i scala-2.11.5.deb && \
    rm scala-2.11.5.deb

# Dirs
RUN mkdir /source

ADD project /source/project
ADD build.sbt /source/build.sbt
ADD run_tests.sh /source/run_tests.sh

# Dependencies
RUN cd /source && sbt update

# Envs
ENV TEST_TYPE "spec"
ENV DOMAIN "http://172.17.42.1"

WORKDIR /source
VOLUME ["/source", "/source/target/scala-2.10", "/root/.ivy2/cache"]

CMD ["/source/run_tests.sh"]

EXPOSE 8080
